### ISSUE TITLE
Tea Cozy (BWS)

### ISSUE THREAD

**Issue by asadmehdi785** [lizzwhitacre/tea_cozy#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 4
* _Comment(s):_ HTML implementation enables proper use of flexbox. HTML structure reflects the grouping and flow of content in the web browser.
 
### Criteria 2: Visual Layout
* _Score Level:_ 3
* _Comment(s):_ Layout matches the design spec in all sections except for one: the copyright section.
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4
* _Comment(s):_ Flexbox properties are correctly applied to flex containers and flex items throughout. Flexbox is used properly and is the primary way of positioning.

### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ The page includes all style and content provided in the design specification.
 
### Overall Score: 15/16
Excellent work with this project! Your HTML and CSS were readable and clean, and I liked how you included comments to separate the code for different aspects of the page! In addition, I liked the use of the `alt` attribute for the images on the webpage. You did a good job making use of flexbox to position different elements on the webpage, and it's clear you put a lot of effort into making the webpage match the specification as closely as possible. Well done!

There was just one part of the page that didn't seem to match the specification exactly, and it was the copyright part at the end:

![image](https://user-images.githubusercontent.com/16052289/44561249-e440a000-a721-11e8-8375-3c2d67342011.png)

We would want the copyright text to be closer to the left-hand part of the screen, as shown in the specification:

![image](https://user-images.githubusercontent.com/16052289/44561267-ff131480-a721-11e8-857e-919fd9a70c56.png)

However, this is a rather minor issue, and the rest of the page looks great. Nice job with that!

Finally, you did a good job making use of HTML5 elements such as `header` and `nav`. Try making use of other such elements like `footer`, `section`, and `figure` in the future as well. Using these elements can help make your webpage more accessible and can reduce the reliance on `div` tags.

Great work overall! I hope you enjoy the rest of the course!

**Comment by ewhitacre0215** [comment]
Thank you for the feedback!
